name: "mender.io script action"
description: "Build and publish mender.io scripts"
author: "Steven Leadbeater <info@ledsysconsultancy.com>"
inputs:
  artifact_name:
    description: 'Name of the script artifact to deploy to mender'
    required: true
    default: '.'
  device_type:
    description: 'Device type for categorization of targets in mender'
    required: true
  packages:
    description: 'Space delimited list of scripts to include in the artifact'
    required: true
    default: ''
  server_address:
    description: 'Address of the mender server to upload to'
    required: true
    default: 'https://hosted.mender.io'
  username:
    description: 'Username on the server specified in the server_address'
    required: true
    default: ''
  password:
    description: 'Password for the user on the server specified in the server_address'
    required: true
    default: ''
  ca_certificate:
    description: 'Certificate file for OS mender'
    required: false
    default: ''

branding:
  icon: "anchor"
  color: "blue"

runs:
  using: docker
  image: docker://ledsys/mender-io-script-action:0.0.1